-- Generated by migration/convert-pg-to-mysql.mjs — do not edit by hand.
-- Target: MySQL 8+ (utf8mb4).
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `admin_login_attempts`;
CREATE TABLE `admin_login_attempts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(191) NOT NULL,
  `success` TINYINT(1) NOT NULL,
  `attempted_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  `user_id` TEXT,
  `email` TEXT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `admin_users`;
CREATE TABLE `admin_users` (
  `id` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `password_hash` TEXT NOT NULL,
  `name` TEXT NOT NULL,
  `is_active` TINYINT(1) DEFAULT true NOT NULL,
  `created_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  `last_login_at` TIMESTAMP(6),
  `totp_secret` TEXT,
  `totp_enabled` TINYINT(1) DEFAULT false NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(160) NOT NULL,
  `parent_id` VARCHAR(191),
  `sort_order` INT DEFAULT 0 NOT NULL,
  `image_url` TEXT,
  `is_featured` TINYINT(1) DEFAULT false NOT NULL,
  `created_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `category_translations`;
CREATE TABLE `category_translations` (
  `id` VARCHAR(191) NOT NULL,
  `category_id` VARCHAR(191) NOT NULL,
  `locale` VARCHAR(8) NOT NULL,
  `name` TEXT NOT NULL,
  `description` TEXT,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`category_id`, `locale`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `contact_messages`;
CREATE TABLE `contact_messages` (
  `id` VARCHAR(191) NOT NULL,
  `name` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `phone` TEXT,
  `postal` TEXT,
  `message` TEXT NOT NULL,
  `status` ENUM('NEW', 'READ', 'REPLIED', 'ARCHIVED') DEFAULT 'NEW' NOT NULL,
  `locale` VARCHAR(8) DEFAULT 'fr' NOT NULL,
  `created_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `invoice_items`;
CREATE TABLE `invoice_items` (
  `id` VARCHAR(191) NOT NULL,
  `invoice_id` VARCHAR(191) NOT NULL,
  `description` TEXT NOT NULL,
  `sku` TEXT,
  `unit_price_cents` INT DEFAULT 0 NOT NULL,
  `quantity` INT DEFAULT 1 NOT NULL,
  `line_total_cents` INT DEFAULT 0 NOT NULL,
  `sort_order` INT DEFAULT 0 NOT NULL,
  `created_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `invoices`;
CREATE TABLE `invoices` (
  `id` VARCHAR(191) NOT NULL,
  `invoice_number` VARCHAR(191) NOT NULL,
  `order_id` VARCHAR(191),
  `status` ENUM('DRAFT', 'ISSUED', 'PAID', 'CANCELLED') DEFAULT 'DRAFT' NOT NULL,
  `customer_name` TEXT NOT NULL,
  `customer_email` TEXT,
  `customer_phone` TEXT,
  `customer_address` TEXT,
  `customer_postal` TEXT,
  `customer_city` TEXT,
  `customer_country` TEXT DEFAULT 'FR',
  `issued_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  `due_at` TIMESTAMP(6),
  `paid_at` TIMESTAMP(6),
  `currency` VARCHAR(3) DEFAULT 'EUR' NOT NULL,
  `vat_rate_percent` DECIMAL(5,2) DEFAULT 20 NOT NULL,
  `subtotal_ht_cents` INT DEFAULT 0 NOT NULL,
  `vat_cents` INT DEFAULT 0 NOT NULL,
  `total_ttc_cents` INT DEFAULT 0 NOT NULL,
  `notes` TEXT,
  `terms` TEXT,
  `footer` TEXT,
  `created_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`invoice_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `newsletter_subscribers`;
CREATE TABLE `newsletter_subscribers` (
  `email` VARCHAR(160) NOT NULL,
  `locale` VARCHAR(8) DEFAULT 'fr' NOT NULL,
  `subscribed_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  `unsubscribed_at` TIMESTAMP(6),
  PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `order_items`;
CREATE TABLE `order_items` (
  `id` VARCHAR(191) NOT NULL,
  `order_id` VARCHAR(191) NOT NULL,
  `product_id` VARCHAR(191),
  `product_name` TEXT NOT NULL,
  `product_slug` TEXT,
  `product_sku` TEXT,
  `unit_price_cents` INT NOT NULL,
  `quantity` INT DEFAULT 1 NOT NULL,
  `line_total_cents` INT NOT NULL,
  `created_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `id` VARCHAR(191) NOT NULL,
  `order_number` VARCHAR(24) NOT NULL,
  `customer_name` TEXT,
  `customer_email` TEXT,
  `status` ENUM('PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED') DEFAULT 'PENDING' NOT NULL,
  `total_cents` INT NOT NULL,
  `items_count` INT DEFAULT 1 NOT NULL,
  `currency` VARCHAR(3) DEFAULT 'EUR' NOT NULL,
  `created_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  `customer_phone` TEXT,
  `shipping_address` TEXT,
  `shipping_postal` TEXT,
  `shipping_city` TEXT,
  `shipping_country` TEXT DEFAULT 'FR',
  `notes` TEXT,
  `paid_at` TIMESTAMP(6),
  `shipped_at` TIMESTAMP(6),
  `delivered_at` TIMESTAMP(6),
  `invoice_number` VARCHAR(191),
  `invoice_issued_at` TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY (`order_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `payment_methods`;
CREATE TABLE `payment_methods` (
  `id` VARCHAR(191) NOT NULL,
  `kind` ENUM('BANK') DEFAULT 'BANK' NOT NULL,
  `label` TEXT NOT NULL,
  `holder` TEXT,
  `bank_name` TEXT,
  `iban` TEXT,
  `bic` TEXT,
  `notes` TEXT,
  `is_default` TINYINT(1) DEFAULT false NOT NULL,
  `is_active` TINYINT(1) DEFAULT true NOT NULL,
  `sort_order` INT DEFAULT 0 NOT NULL,
  `created_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `product_media`;
CREATE TABLE `product_media` (
  `id` VARCHAR(191) NOT NULL,
  `product_id` VARCHAR(191) NOT NULL,
  `url` TEXT NOT NULL,
  `alt_text` TEXT,
  `type` ENUM('IMAGE', 'VIDEO') DEFAULT 'IMAGE' NOT NULL,
  `sort_order` INT DEFAULT 0 NOT NULL,
  `is_lifestyle` TINYINT(1) DEFAULT false NOT NULL,
  `is_cover` TINYINT(1) DEFAULT false NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `product_translations`;
CREATE TABLE `product_translations` (
  `id` VARCHAR(191) NOT NULL,
  `product_id` VARCHAR(191) NOT NULL,
  `locale` VARCHAR(8) NOT NULL,
  `name` TEXT NOT NULL,
  `short_desc` TEXT,
  `description` TEXT,
  `features_json` JSON,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`product_id`, `locale`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `id` VARCHAR(191) NOT NULL,
  `sku` VARCHAR(64) NOT NULL,
  `slug` VARCHAR(200) NOT NULL,
  `category_id` VARCHAR(191) NOT NULL,
  `status` ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED') DEFAULT 'DRAFT' NOT NULL,
  `base_price_cents` INT NOT NULL,
  `currency` VARCHAR(3) DEFAULT 'EUR' NOT NULL,
  `stock` INT DEFAULT 0 NOT NULL,
  `weight_grams` INT,
  `is_configurable` TINYINT(1) DEFAULT false NOT NULL,
  `is_featured` TINYINT(1) DEFAULT false NOT NULL,
  `family` VARCHAR(40),
  `material` VARCHAR(16),
  `colorway` VARCHAR(20),
  `finish` VARCHAR(64),
  `width_ft` INT,
  `length_ft` INT,
  `width_cm` INT,
  `length_cm` INT,
  `published_at` TIMESTAMP(6),
  `created_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`sku`),
  UNIQUE KEY (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `public_submissions`;
CREATE TABLE `public_submissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `kind` VARCHAR(191) NOT NULL,
  `ip` VARCHAR(191) NOT NULL,
  `submitted_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  CONSTRAINT public_submissions_kind_check CHECK (kind IN ('contact', 'newsletter')),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `site_settings`;
CREATE TABLE `site_settings` (
  `key` VARCHAR(96) NOT NULL,
  `value` JSON NOT NULL,
  `updated_at` TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `admin_login_attempts_ip_time_idx` ON `admin_login_attempts` (`ip`, `attempted_at`);
CREATE INDEX `admin_users_email_idx` ON `admin_users` (`email`);
CREATE INDEX `categories_featured_idx` ON `categories` (`is_featured`);
CREATE INDEX `categories_parent_idx` ON `categories` (`parent_id`);
CREATE INDEX `contact_messages_created_idx` ON `contact_messages` (`created_at`);
CREATE INDEX `contact_messages_status_idx` ON `contact_messages` (`status`);
CREATE INDEX `invoice_items_invoice_idx` ON `invoice_items` (`invoice_id`);
CREATE INDEX `invoices_issued_idx` ON `invoices` (`issued_at`);
CREATE INDEX `invoices_order_idx` ON `invoices` (`order_id`);
CREATE INDEX `invoices_status_idx` ON `invoices` (`status`);
CREATE INDEX `order_items_order_idx` ON `order_items` (`order_id`);
CREATE INDEX `orders_created_idx` ON `orders` (`created_at`);
CREATE UNIQUE INDEX `orders_invoice_number_unique` ON `orders` (`invoice_number`);
CREATE INDEX `orders_status_idx` ON `orders` (`status`);
CREATE INDEX `payment_methods_active_idx` ON `payment_methods` (`is_active`, `sort_order`);
CREATE INDEX `payment_methods_default_idx` ON `payment_methods` (`is_default`);
CREATE INDEX `product_media_product_idx` ON `product_media` (`product_id`);
CREATE INDEX `products_category_status_idx` ON `products` (`category_id`, `status`);
CREATE INDEX `products_featured_status_idx` ON `products` (`is_featured`, `status`);
CREATE INDEX `products_published_idx` ON `products` (`published_at`);
CREATE INDEX `public_submissions_kind_ip_time_idx` ON `public_submissions` (`kind`, `ip`, `submitted_at`);

SET FOREIGN_KEY_CHECKS = 1;