import type { PergolaProduct } from "./types";

const ft = (x: number) => Math.round(x * 30.48);

// EUR prices ≈ USD × 0.95 rounded to nearest 10, sourced from
// backyarddiscovery.com/collections/pergolas (Nov 2026 snapshot).
export const catalog: PergolaProduct[] = [
  // ── Beaumont — cedar classic ──────────────────────────────────
  {
    slug: "beaumont-10x10",
    sku: "BMT-10X10",
    family: "beaumont",
    material: "wood",
    category: "pergola-bois",
    name: "Pergola Beaumont 10×10",
    tagline: "Pergola cèdre traditionnelle, parfaite pour les petits jardins.",
    widthFt: 10,
    lengthFt: 10,
    widthCm: ft(10),
    lengthCm: ft(10),
    priceCents: 105000,
    imageCount: 3,
    colorway: "warm-cedar",
  },
  {
    slug: "beaumont-12x10",
    sku: "BMT-12X10",
    family: "beaumont",
    material: "wood",
    category: "pergola-bois",
    name: "Pergola Beaumont 12×10",
    tagline: "Cèdre massif, un sanctuaire d'extérieur intimiste.",
    widthFt: 12,
    lengthFt: 10,
    widthCm: ft(12),
    lengthCm: ft(10),
    priceCents: 115000,
    imageCount: 3,
    colorway: "warm-cedar",
  },
  {
    slug: "beaumont-12x12",
    sku: "BMT-12X12",
    family: "beaumont",
    material: "wood",
    category: "pergola-bois",
    name: "Pergola Beaumont 12×12",
    tagline: "Retraite carrée en cèdre pour recevoir en toute élégance.",
    widthFt: 12,
    lengthFt: 12,
    widthCm: ft(12),
    lengthCm: ft(12),
    priceCents: 133000,
    imageCount: 3,
    featured: true,
    colorway: "warm-cedar",
  },
  {
    slug: "beaumont-14x10",
    sku: "BMT-14X10",
    family: "beaumont",
    material: "wood",
    category: "pergola-bois",
    name: "Pergola Beaumont 14×10",
    tagline: "Le format classique, taillé pour un salon d'extérieur complet.",
    widthFt: 14,
    lengthFt: 10,
    widthCm: ft(14),
    lengthCm: ft(10),
    priceCents: 124000,
    imageCount: 4,
    featured: true,
    colorway: "warm-cedar",
  },
  {
    slug: "beaumont-14x12",
    sku: "BMT-14X12",
    family: "beaumont",
    material: "wood",
    category: "pergola-bois",
    name: "Pergola Beaumont 14×12",
    tagline: "Cèdre intemporel, pensée pour la salle à manger d'été.",
    widthFt: 14,
    lengthFt: 12,
    widthCm: ft(14),
    lengthCm: ft(12),
    priceCents: 152000,
    imageCount: 3,
    colorway: "warm-cedar",
  },
  {
    slug: "beaumont-16x12",
    sku: "BMT-16X12",
    family: "beaumont",
    material: "wood",
    category: "pergola-bois",
    name: "Pergola Beaumont 16×12",
    tagline: "Charme rustique et robustesse pour les grandes tablées.",
    widthFt: 16,
    lengthFt: 12,
    widthCm: ft(16),
    lengthCm: ft(12),
    priceCents: 162000,
    imageCount: 3,
    colorway: "warm-cedar",
  },
  {
    slug: "beaumont-20x12",
    sku: "BMT-20X12",
    family: "beaumont",
    material: "wood",
    category: "pergola-bois",
    name: "Pergola Beaumont 20×12",
    tagline: "Format généreux, transforme le jardin en pièce à vivre.",
    widthFt: 20,
    lengthFt: 12,
    widthCm: ft(20),
    lengthCm: ft(12),
    priceCents: 199000,
    imageCount: 3,
    colorway: "warm-cedar",
  },
  {
    slug: "beaumont-24x12",
    sku: "BMT-24X12",
    family: "beaumont",
    material: "wood",
    category: "pergola-bois",
    name: "Pergola Beaumont 24×12",
    tagline: "L'imposante, dessinée pour recevoir toute l'année.",
    widthFt: 24,
    lengthFt: 12,
    widthCm: ft(24),
    lengthCm: ft(12),
    priceCents: 228000,
    imageCount: 3,
    colorway: "warm-cedar",
  },

  // ── Ashland — trellis roof, rustic charm ─────────────────────
  {
    slug: "ashland-14x10",
    sku: "ASH-14X10",
    family: "ashland",
    material: "wood",
    category: "pergola-bois",
    name: "Pergola Ashland 14×10",
    tagline: "Cèdre & toit à claire-voie, un charme intemporel.",
    widthFt: 14,
    lengthFt: 10,
    widthCm: ft(14),
    lengthCm: ft(10),
    priceCents: 143000,
    imageCount: 4,
    featured: true,
    colorway: "warm-cedar",
  },

  // ── Somerville — classic detail ──────────────────────────────
  {
    slug: "somerville-14x10-barnwood",
    sku: "SVL-14X10-BW",
    family: "somerville",
    material: "wood",
    category: "pergola-bois",
    name: "Pergola Somerville 14×10 — Teinte Barnwood",
    tagline: "Charme classique, détails soignés, oasis d'extérieur.",
    widthFt: 14,
    lengthFt: 10,
    widthCm: ft(14),
    lengthCm: ft(10),
    priceCents: 114000,
    imageCount: 3,
    finish: "Barnwood",
    colorway: "barnwood",
  },
  {
    slug: "somerville-14x10-walnut",
    sku: "SVL-14X10-WN",
    family: "somerville",
    material: "wood",
    category: "pergola-bois",
    name: "Pergola Somerville 14×10 — Teinte Noyer",
    tagline: "Cèdre teinté noyer, détails traditionnels, invitation naturelle.",
    widthFt: 14,
    lengthFt: 10,
    widthCm: ft(14),
    lengthCm: ft(10),
    priceCents: 114000,
    imageCount: 3,
    finish: "Noyer",
    colorway: "walnut",
  },

  // ── Delray — wide purlin canopy ──────────────────────────────
  {
    slug: "delray-14x10",
    sku: "DEL-14X10",
    family: "delray",
    material: "wood",
    category: "pergola-bois",
    name: "Pergola Delray 14×10",
    tagline: "Larges lambourdes en cèdre pour une canopée généreuse.",
    widthFt: 14,
    lengthFt: 10,
    widthCm: ft(14),
    lengthCm: ft(10),
    priceCents: 143000,
    imageCount: 3,
    colorway: "warm-cedar",
  },

  // ── Brendan — sail shade, entry-level ────────────────────────
  {
    slug: "brendan-12x10",
    sku: "BRD-12X10",
    family: "brendan",
    material: "wood",
    category: "pergola-bois",
    name: "Pergola Brendan 12×10 — Voile d'ombrage",
    tagline: "Cèdre moderne, canopée tissée premium, élégance décontractée.",
    widthFt: 12,
    lengthFt: 10,
    widthCm: ft(12),
    lengthCm: ft(10),
    priceCents: 67000,
    imageCount: 3,
    colorway: "warm-cedar",
  },

  // ── Sarasota — steel louvered, modern ────────────────────────
  {
    slug: "sarasota-10x10",
    sku: "SRT-10X10",
    family: "sarasota",
    material: "steel",
    category: "pergola-lame-orientable",
    name: "Pergola Sarasota 10×10 — Lames orientables",
    tagline: "Acier galvanisé noir, lames pilotables, confort tout-temps.",
    widthFt: 10,
    lengthFt: 10,
    widthCm: ft(10),
    lengthCm: ft(10),
    priceCents: 181000,
    imageCount: 3,
    colorway: "black",
  },
  {
    slug: "sarasota-12x10",
    sku: "SRT-12X10",
    family: "sarasota",
    material: "steel",
    category: "pergola-lame-orientable",
    name: "Pergola Sarasota 12×10 — Lames orientables",
    tagline: "Design moderne noir, refuge d'extérieur intimiste.",
    widthFt: 12,
    lengthFt: 10,
    widthCm: ft(12),
    lengthCm: ft(10),
    priceCents: 190000,
    imageCount: 3,
    colorway: "black",
  },
  {
    slug: "sarasota-14x10",
    sku: "SRT-14X10",
    family: "sarasota",
    material: "steel",
    category: "pergola-lame-orientable",
    name: "Pergola Sarasota 14×10 — Lames orientables",
    tagline: "Acier durable, lames réglables, plaisir 12 mois sur 12.",
    widthFt: 14,
    lengthFt: 10,
    widthCm: ft(14),
    lengthCm: ft(10),
    priceCents: 209000,
    imageCount: 3,
    featured: true,
    colorway: "black",
  },
  {
    slug: "sarasota-16x10",
    sku: "SRT-16X10",
    family: "sarasota",
    material: "steel",
    category: "pergola-lame-orientable",
    name: "Pergola Sarasota 16×10 — Lames orientables",
    tagline: "Contemporaine, robuste, toutes saisons.",
    widthFt: 16,
    lengthFt: 10,
    widthCm: ft(16),
    lengthCm: ft(10),
    priceCents: 228000,
    imageCount: 3,
    colorway: "black",
  },
  {
    slug: "sarasota-18x10",
    sku: "SRT-18X10",
    family: "sarasota",
    material: "steel",
    category: "pergola-lame-orientable",
    name: "Pergola Sarasota 18×10 — Lames orientables",
    tagline: "Espace généreux, ligne sombre affirmée.",
    widthFt: 18,
    lengthFt: 10,
    widthCm: ft(18),
    lengthCm: ft(10),
    priceCents: 247000,
    imageCount: 3,
    colorway: "black",
  },
  {
    slug: "sarasota-20x10",
    sku: "SRT-20X10",
    family: "sarasota",
    material: "steel",
    category: "pergola-lame-orientable",
    name: "Pergola Sarasota 20×10 — Lames orientables",
    tagline: "Lignes épurées, format panoramique pour recevoir.",
    widthFt: 20,
    lengthFt: 10,
    widthCm: ft(20),
    lengthCm: ft(10),
    priceCents: 266000,
    imageCount: 3,
    colorway: "black",
  },

  // ── Evanston — wall-mounted louvered ─────────────────────────
  {
    slug: "evanston-10x10",
    sku: "EVN-10X10",
    family: "evanston",
    material: "steel",
    category: "pergola-adossee",
    name: "Pergola Evanston 10×10 — Adossée à lames",
    tagline: "Adossée murale, lames pilotables, idéale terrasse compacte.",
    widthFt: 10,
    lengthFt: 10,
    widthCm: ft(10),
    lengthCm: ft(10),
    priceCents: 152000,
    imageCount: 3,
    colorway: "black",
  },
  {
    slug: "evanston-12x10",
    sku: "EVN-12X10",
    family: "evanston",
    material: "steel",
    category: "pergola-adossee",
    name: "Pergola Evanston 12×10 — Adossée à lames",
    tagline: "Ombrage modulable, style contemporain, montage mural.",
    widthFt: 12,
    lengthFt: 10,
    widthCm: ft(12),
    lengthCm: ft(10),
    priceCents: 171000,
    imageCount: 3,
    colorway: "black",
  },
  {
    slug: "evanston-14x10",
    sku: "EVN-14X10",
    family: "evanston",
    material: "steel",
    category: "pergola-adossee",
    name: "Pergola Evanston 14×10 — Adossée à lames",
    tagline: "Acier noir contemporain, toit à lames, fixation façade.",
    widthFt: 14,
    lengthFt: 10,
    widthCm: ft(14),
    lengthCm: ft(10),
    priceCents: 190000,
    imageCount: 3,
    featured: true,
    colorway: "black",
  },
  {
    slug: "evanston-16x10",
    sku: "EVN-16X10",
    family: "evanston",
    material: "steel",
    category: "pergola-adossee",
    name: "Pergola Evanston 16×10 — Adossée à lames",
    tagline: "Galvanisé durable, format familial, mural.",
    widthFt: 16,
    lengthFt: 10,
    widthCm: ft(16),
    lengthCm: ft(10),
    priceCents: 209000,
    imageCount: 3,
    colorway: "black",
  },
  {
    slug: "evanston-18x10",
    sku: "EVN-18X10",
    family: "evanston",
    material: "steel",
    category: "pergola-adossee",
    name: "Pergola Evanston 18×10 — Adossée à lames",
    tagline: "Modernité et élégance, espace pour recevoir.",
    widthFt: 18,
    lengthFt: 10,
    widthCm: ft(18),
    lengthCm: ft(10),
    priceCents: 228000,
    imageCount: 3,
    colorway: "black",
  },
  {
    slug: "evanston-20x10",
    sku: "EVN-20X10",
    family: "evanston",
    material: "steel",
    category: "pergola-adossee",
    name: "Pergola Evanston 20×10 — Adossée à lames",
    tagline: "Adossée grand format, couverture ample, style raffiné.",
    widthFt: 20,
    lengthFt: 10,
    widthCm: ft(20),
    lengthCm: ft(10),
    priceCents: 238000,
    imageCount: 3,
    colorway: "black",
  },

  // ── Windham — white galvanized steel ─────────────────────────
  {
    slug: "windham-14x10",
    sku: "WDH-14X10",
    family: "windham",
    material: "steel",
    category: "pergola-aluminium",
    name: "Pergola Windham 14×10 — Voile d'ombrage",
    tagline: "Acier galvanisé blanc, ligne aérienne, voile tendue.",
    widthFt: 14,
    lengthFt: 10,
    widthCm: ft(14),
    lengthCm: ft(10),
    priceCents: 109000,
    imageCount: 3,
    colorway: "white",
  },
  {
    slug: "windham-14x12",
    sku: "WDH-14X12",
    family: "windham",
    material: "steel",
    category: "pergola-aluminium",
    name: "Pergola Windham 14×12 — Voile d'ombrage",
    tagline: "Galvanisé toutes saisons, format généreux.",
    widthFt: 14,
    lengthFt: 12,
    widthCm: ft(14),
    lengthCm: ft(12),
    priceCents: 114000,
    imageCount: 3,
    colorway: "white",
  },

  // ── Cabana corner ────────────────────────────────────────────
  {
    slug: "tuscany-corner",
    sku: "TSC-CORNER",
    family: "tuscany",
    material: "wood",
    category: "pergola-cabana",
    name: "Pergola d'angle Tuscany",
    tagline: "Cèdre robuste, panneaux bambou, assise intégrée.",
    widthFt: 13,
    lengthFt: 8,
    widthCm: ft(13),
    lengthCm: ft(8),
    priceCents: 124000,
    imageCount: 3,
    featured: true,
    colorway: "warm-cedar",
  },
  {
    slug: "verona-corner",
    sku: "VRN-CORNER",
    family: "verona",
    material: "wood",
    category: "pergola-cabana",
    name: "Pergola d'angle Verona",
    tagline: "Cèdre rustique, panneaux d'intimité, sanctuaire intimiste.",
    widthFt: 13,
    lengthFt: 8,
    widthCm: ft(13),
    lengthCm: ft(8),
    priceCents: 114000,
    imageCount: 3,
    colorway: "warm-cedar",
  },
];

export const getProductBySlug = (slug: string) =>
  catalog.find((p) => p.slug === slug);

export const getRelatedProducts = (product: PergolaProduct, limit = 3) =>
  catalog
    .filter((p) => p.slug !== product.slug && p.family === product.family)
    .concat(
      catalog.filter(
        (p) => p.slug !== product.slug && p.material === product.material,
      ),
    )
    .filter((p, i, a) => a.findIndex((x) => x.slug === p.slug) === i)
    .slice(0, limit);
